<?php
/**
 * Created by PhpStorm.
 * User: zolkinka
 * Date: 02.02.18
 * Time: 20:48
 */
namespace App;

class Library
{
public static $L = ['Ts' => ['value' => 0,
'show' => 'Т<sub>с</sub>',
'type' => 'date',
    'random'=>[[1053435600,1053993600],[1066309200,1066953600]]],
    'N' => ['value' => 0,
'show' => 'N<sub>п</sub>',
'type' => 'N',
        'random'=>[[-12,12]]],
    'Tgr' => ['value' => 0,
'show' => 'Т<sub>Гр</sub>',
'type' => 'date','random'=>[[1053435600,1053993600],[1066309200,1066953600]]],
    'Tgr0' => ['value' => 0,
'show' => 'Т<sub>Гр</sub>',
'type' => 'date', 'random'=>[[1053435600,1053514800]]],
    'dT' => ['value' => -1,
'show' => 'ΔТ',
'type' => 'minsec',
        'random'=>[[15,1200]]],
    'St' => ['value' => 0,
'show' => 'S<sub>табл</sub>',
'type' => 'dm',
        'MAE'=>'St'],
    'St2' => ['value' => 0,
'show' => 'S<sub>табл</sub>',
'type' => 'dm'],
    'dS' => ['value' => 3,
'show' => 'ΔS',
'type' => 'dm', 'MAE'=>'dS'],
    'Sgr' => ['value' => 5,
'show' => 'S<sub>Гр</sub>',
'type' => 'dm'],
    'Sm' => ['value' => 5,
'show' => 'S<sub>м</sub>',
'type' => 'dm'],
    'lng' => ['value' => 170,
'show' => 'λ',
'type' => 'lng', 'random'=>[[-17000, 17000]]],
    'tau' => ['value' => 5,
'show' => 'τ',
'type' => 'dm','random'=>[[1000,35000]]],
    'tm' => ['value' => 5,
'show' => 't<sub>м</sub>',
'type' => 'dm'],
    'tmW' => ['value' => 5,
'show' => 't<sub>W</sub>',
'type' => 'dm'],
    'tmE' => ['value' => 5,
'show' => 't<sub>E</sub>',
'type' => 'dm'],
    'tgr' => ['value' => 5,
'show' => 't<sub>Гр</sub>',
'type' => 'dm', 'random'=>[[10,350]]],
    'tt' => ['value' => 5,
'show' => 't<sub>т</sub>',
'type' => 'dm'],
    'dtt' => ['value' => 5,
'show' => 'Δt',
'type' => 'm+'],
    'dt1' => ['value' => 5,
'show' => 'Δt<sub>1</sub>',
'type' => 'dm', 'MAE'=>'dt1'],
    'dt2' => ['value' => 5,
'show' => 'Δt<sub>2</sub>',
'type' => 'dm', 'MAE'=>'dt2'],
    'db' => ['value' => 5,
'show' => 'Δb',
'type' => 'm+', 'MAE'=>'db'],
    'dbt' => ['value' => 5,
'show' => 'Δb',
'type' => 'm+', 'MAE'=>'dbt'],
    'tpr' => ['value' => 5,
'show' => 't<sub>пр</sub>',
'type' => 'lng', 'random'=>[[-17000, 17000]]],
    'b' => ['value' => 5,
'show' => 'b<sub>пр</sub>',
'type' => 'lat', 'MAE'=>'b', 'random'=>[[-7000,7000]]],
    'h' => ['value' => 5,
'show' => 'h',
'type' => 'dm+'],
    'hv' => ['value' => 5,
'show' => 'h<sub>В</sub>',
'type' => 'dm+'],
    'lat' => ['value' => 5,
'show' => '&phi;',
'type' => 'lat', 'random'=>[[-7000, 7000]]],
    'lat0' => ['value' => 5,
'show' => '&phi;',
'type' => 'lat', 'random'=>[[-4500, 4500]]],
    'dhi' => ['value' => 5,
'show' => 'Δh<sub>i</sub>',
'type' => 'm+'],
    'dhid' => ['value' => 5,
'show' => 'Δh<sub>i+d</sub>',
'type' => 'm+'],
    'dhd' => ['value' => 5,
'show' => 'Δh<sub>d</sub>',
'type' => 'm+'],
    'dhp' => ['value' => 5,
'show' => 'Δh<sub>p</sub>',
'type' => 'm+'],
    'dht' => ['value' => 5,
'show' => 'Δh<sub>t</sub>',
'type' => 'm+'],
    'dhb' => ['value' => 5,
'show' => 'Δh<sub>B</sub>',
'type' => 'm+'],
    'dhbt' => ['value' => 5,
'show' => 'Δh<sub>Bt</sub>',
'type' => 'm+'],
    'dhz' => ['value' => 5,
'show' => 'Δh<sub>z</sub>',
'type' => 'm+'],
'ho' => ['value' => 5,
'show' => 'h<sub>o</sub>',
'type' => 'dm+'],
'hs1' => ['value' => 15,
'show' => 'h<sub>c</sub>',
'type' => 'dm+'],
'OS1' => ['value' => 0,
'show' => 'ОС<sub>1</sub>',
'type' => 'dm+'],
'OS2' => ['value' => 0,
'show' => 'ОС<sub>2</sub>',
'type' => 'dm+'],
'OS3' => ['value' => 0,
'show' => 'ОС<sub>3</sub>',
'type' => 'dm+'],
'OS4' => ['value' => 0,
'show' => 'ОС<sub>4</sub>',
'type' => 'dm+'],
    'OS' => ['value' => 0,
'show' => 'ОС',
'type' => 'dm+', 'random'=>[[1000,6000]]],
'n' => ['value' => 5,
'show' => 'n',
'type' => 'm+'],
'Oisr' => ['value' => 0,
'show' => 'O<sub>iср</sub>',
'type' => 'dm', 'random'=>[[35970, 35999],[36010,36030]]],
'Tstart' => ['value' => 0,
'show' => 'T<sub>ст</sub>',
'type' => 'date', 'random'=>[[1053435600,1053993600],[1066309200,1066953600]]],
'PU' => ['value' => 0,
'show' => 'ПУ',
'type' => 'deg', 'random'=>[[10,350]]],
'V' => ['value' => 0,
'show' => 'V',
'type' => 'deg', 'random'=>[[5,25]]],
'e' => ['value' => 0,
'show' => 'e',
'type' => 'deg', 'random'=>[[4,20]]],
'B' => ['value' => 0,
'show' => 'B',
'type' => 'deg', 'random'=>[[726,774]]],
    'temp' => ['value' => 0,
'show' => 't',
'type' => 'deg', 'random'=>[[-24,34]]],
    'star1Num' => ['value' => 0,
'show' => 't',
'type' => 'deg'], 'star2Num' => ['value' => 0,
'show' => 't',
'type' => 'deg'], 'star3Num' => ['value' => 0,
'show' => 't',
'type' => 'deg'], 'star4Num' => ['value' => 0,
'show' => 't',
'type' => 'deg'], 'tau1' => ['value' => 0,
'show' => 'τ<sub>1</sub>',
'type' => 'dm'], 'tau2' => ['value' => 0,
'show' => 'τ<sub>2</sub>',
'type' => 'dm'], 'tau3' => ['value' => 0,
'show' => 'τ<sub>3</sub>',
'type' => 'dm'], 'tau4' => ['value' => 0,
'show' => 'τ<sub>4</sub>',
'type' => 'dm'], 'b1' => ['value' => 0,
'show' => '&delta;<sub>1</sub>',
'type' => 'lat'], 'b2' => ['value' => 0,
'show' => '&delta;<sub>2</sub>',
'type' => 'lat'], 'b3' => ['value' => 0,
'show' => '&delta;<sub>3</sub>',
'type' => 'lat'], 'b4' => ['value' => 0,
'show' => '&delta;<sub>4</sub>',
'type' => 'lat'], 'A1' => ['value' => 0,
'show' => 'A<sub>1</sub>',
'type' => 'deg'], 'A2' => ['value' => 0,
'show' => 'A<sub>2</sub>',
'type' => 'deg'], 'A3' => ['value' => 0,
'show' => 'A<sub>3</sub>',
'type' => 'deg'], 'A4' => ['value' => 0,
'show' => 'A<sub>4</sub>',
'type' => 'deg'], 'ho1' => ['value' => 0,
'show' => 'ho<sub>1</sub>',
'type' => 'dm'], 'ho2' => ['value' => 0,
'show' => 'ho<sub>2</sub>',
'type' => 'dm'], 'ho3' => ['value' => 0,
'show' => 'ho<sub>3</sub>',
'type' => 'dm'], 'ho4' => ['value' => 0,
'show' => 'ho<sub>4</sub>',
'type' => 'dm'], 'hc1' => ['value' => 0,
'show' => 'hc<sub>1</sub>',
'type' => 'dm'], 'hc2' => ['value' => 0,
'show' => 'hc<sub>2</sub>',
'type' => 'dm'], 'hc3' => ['value' => 0,
'show' => 'hc<sub>3</sub>',
'type' => 'dm'], 'hc' => ['value' => 0,
'show' => 'hc<sub>4</sub>',
'type' => 'dm+'], 'n1' => ['value' => 0,
'show' => 'n<sub>1</sub>',
'type' => 'dm+'], 'n2' => ['value' => 0,
'show' => 'n<sub>2</sub>',
'type' => 'dm+'], 'n3' => ['value' => 0,
'show' => 'n<sub>3</sub>',
'type' => 'dm+'], 'n4' => ['value' => 0,
'show' => 'n<sub>4</sub>',
'type' => 'dm+'], 'Tgr1' => ['value' => 0,
'show' => 'T<sub>Гр1</sub>',
'type' => 'date'], 'Tgr2' => ['value' => 0,
'show' => 'T<sub>Гр2</sub>',
'type' => 'date'], 'Tgr3' => ['value' => 0,
'show' => 'T<sub>Гр3</sub>',
'type' => 'date'], 'Tgr4' => ['value' => 0,
'show' => 'T<sub>Гр4</sub>',
'type' => 'date'], 'dlat' => ['value' => 0,
'show' => 'Δ&phi;',
'type' => 'm+'], 'lato' => ['value' => 0,
'show' => '&phi;<sub>o</sub>',
'type' => 'lat'], 'domega' => ['value' => 0,
'show' => 'Δ&omega;',
'type' => 'm+'], 'dlng' => ['value' => 0,
'show' => 'Δ&lambda;',
'type' => 'm+'], 'lngo' => ['value' => 0,
'show' => '&lambda;<sub>o</sub>',
'type' => 'lng'], 'P0' => ['value' => 0,
'show' => 'P<sub>0</sub>',
'type' => 'm+'], 'hdop' => ['value' => 0,
'show' => '&Delta;h<sub>доп</sub>',
'type' => 'dm+'],
    'minH'=>[
        'value'=>0,
        'show'=>'',
        'type'=>''
    ],
    'Ao'=>[
        'value'=>0,
        'show'=>'A<sub>o</sub>',
        'type'=>'deg','random'=>[[10,350]]
    ],
    'kvazi'=>[
        'value'=>0,
        'show'=>'&Delta;-',
        'type'=>'dm', 'MAE'=>'kvazi'
    ],'svg'=>[
        'value'=>0,
        'show'=>'&Delta;&delta;',
        'type'=>'dm'
    ],'Tkt'=>[
        'value'=>0,
        'show'=>'T<sub>Табл</sub>',
        'type'=>'date'
    ],'Tkm'=>[
        'value'=>0,
        'show'=>'Tк<sub>м</sub>',
        'type'=>'hm','MAE'=>'Tk'
    ],'Tkgr'=>[
        'value'=>0,
        'show'=>'T<sub>Гр</sub>',
        'type'=>'hm'
    ],'lngH'=>[
        'value'=>0,
        'show'=>'&lambda;',
        'type'=>'hm'
    ],'Tks'=>[
        'value'=>0,
        'show'=>'T<sub>c</sub>',
        'type'=>'hm'
    ],'Tvt1'=>[
        'value'=>0,
        'show'=>'T<sub>в/з1</sub>',
        'type'=>'hm'
    ],'Tvzt1'=>[
        'value'=>0,
        'show'=>'T<sub>в/з</sub>',
        'type'=>'hm','MAE'=>'Tvt1'
    ],'Tvzt2'=>[
        'value'=>0,
        'show'=>'T<sub>в/з2</sub>',
        'type'=>'hm'
    ],'Tvzgr'=>[
        'value'=>0,
        'show'=>'T<sub>Гр</sub>',
        'type'=>'hm'
    ],'Tvzm'=>[
        'value'=>0,
        'show'=>'T<sub>м</sub>',
        'type'=>'hm'
    ],'Tvzs'=>[
        'value'=>0,
        'show'=>'T<sub>c</sub>',
        'type'=>'hm'
    ],'Tvzdlat'=>[
        'value'=>0,
        'show'=>'&Delta;<sub>&phi;</sub>',
        'type'=>'numberM', 'MAE'=>'Tvdlat'
    ],'Tvzds'=>[
        'value'=>0,
        'show'=>'&Delta;<sub>сут</sub>',
        'type'=>'numberM'
    ],'dGKK'=>[
        'value'=>0,
        'show'=>'&Delta;ГКК',
        'type'=>'deg+'
    ],'GKK'=>[
        'value'=>0,
        'show'=>'ГКК',
        'type'=>'deg+'
    ],'VLP'=>[
        'value'=>0,
        'show'=>'ВЛП',
        'type'=>'deg'
    ], 'bo' => ['value' => 0,
        'show' => '&delta;',
        'type' => 'lat'
    ], 'sign' => ['value' => 0,
        'show' => '&delta;',
        'type' => 'deg']
    , 'SQ' => ['value' => 0,
        'show' => '&delta;',
        'type' => 'deg'],
    'Star'=>[
        'value=0',
        'show'=>'',
        'type'=>'text'
    ],


];
}



?>